.TH nova\-rootwrap 8
.SH NAME
nova\-rootwrap \- Authorizes and executes sudo commands on Nova's behalf

.SH SYNOPSIS
.B nova\-rootwrap
.B <command>

.SH DESCRIPTION
.B nova\-rootwrap

This man page is a stub. Please contribute.

.SH PARAMETERS

.LP
.B <command> 
.IP

Command to be executed with sudo
