.TH nova\-consoleauth 8
.SH NAME
nova\-console \- nova VNC console authenticator 

.SH SYNOPSIS
.B nova\-consoleauth
.B \-\-flagfile=<flagfilepath>

.SH DESCRIPTION
.B nova\-consoleauth

This man page is a stub. Please contribute.

.SH PARAMETERS

.LP
.B \-\-flagfile=<flagfilepath>
.IP

Path to the file containing options.
