.TH nova\-api\-os\-compute 8
.SH NAME
nova\-api\-os\-compute \- frontend API server for Nova Compute 

.SH SYNOPSIS
.B nova\-api\-os\-compute
.B \-\-flagfile=<flagfilepath>

.SH DESCRIPTION
.B nova\-api\-os\-compute

This man page is a stub. Please contribute.

.SH PARAMETERS

.LP
.B \-\-flagfile=<flagfilepath>
.IP

Path to the file containing options.
